version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: OmniSharp.Extensions.LanguageClient
    versions:
    - 0.19.0
  - dependency-name: OmniSharp.Extensions.LanguageServer
    versions:
    - 0.19.0
  - dependency-name: OmniSharp.Extensions.DebugAdapter.Server
    versions:
    - 0.19.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: OmniSharp.Extensions.DebugAdapter.Client
    versions:
    - 0.19.0
  - dependency-name: Microsoft.PowerShell.SDK
    versions:
    - 7.1.1
    - 7.1.2
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
